# Generated by Django 3.2.6 on 2024-05-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('position', models.CharField(max_length=75)),
                ('address', models.TextField(blank=True)),
                ('mobile_num', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='duetype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('dueType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.duetype')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.duetype')),
            ],
        ),
    ]
