# Generated by Django 3.2.6 on 2024-05-09 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240509_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.student'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.duetype'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='dueType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.duetype'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.student'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.admin'),
        ),
    ]
