# Generated by Django 3.2.6 on 2024-05-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20240509_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='johndoe@gmail.com', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='johndoe@gmail.com', max_length=150),
        ),
    ]
