# Generated by Django 3.2.6 on 2024-05-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240512_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='block',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
