# Generated by Django 3.2.6 on 2024-05-16 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_basemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseModel',
            new_name='Recents',
        ),
    ]
