# Generated by Django 3.2.6 on 2024-05-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_basemodel_recents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recents',
        ),
    ]
