# Generated by Django 3.2.6 on 2024-05-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='duetype',
            name='fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
