# Generated by Django 3.2.6 on 2024-05-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20240517_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duetype',
            name='fees',
            field=models.IntegerField(default=0),
        ),
    ]
