# Generated by Django 3.2.6 on 2024-05-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_balance_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('event_name', models.CharField(max_length=150)),
                ('date', models.DateTimeField(blank=True)),
                ('announcement', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
