# Generated by Django 3.2.6 on 2024-05-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_transaction_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='address',
        ),
    ]
