# Generated by Django 3.2.6 on 2024-05-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_admin_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='mobile_num',
        ),
    ]
