# Generated by Django 3.2.6 on 2024-05-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20240523_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_num',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
