# Generated by Django 3.2.6 on 2024-05-24 01:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default=uuid.uuid1, max_length=150, unique=True),
        ),
    ]
