# Generated by Django 3.2.6 on 2024-10-03 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0023_auto_20240524_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Fee_name', models.CharField(max_length=75)),
                ('Fee_amount', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Officers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Position', models.CharField(max_length=75)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Student_number', models.CharField(max_length=15, unique=True)),
                ('First_name', models.CharField(max_length=75)),
                ('Last_name', models.CharField(max_length=75)),
                ('Year_level', models.CharField(max_length=75, null=True)),
                ('Corporate_email', models.EmailField(max_length=150, unique=True)),
                ('Password', models.CharField(max_length=75)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Transaction_Date', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.BigIntegerField()),
                ('Status', models.CharField(choices=[('Green', 'Fully Paid'), ('Yellow', 'Partially Paid'), ('Red', 'Unpaid')], default='Red', max_length=10)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.feetype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='home.students')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='type',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='dueType',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payee',
        ),
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.DeleteModel(
            name='DueType',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='transaction',
        ),
        migrations.AddField(
            model_name='officers',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer', to='home.students'),
        ),
        migrations.AddField(
            model_name='officers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
