# Generated by Django 3.2.6 on 2024-10-03 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20241003_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='home.officer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='home.student'),
        ),
    ]
