# Generated by Django 3.2.6 on 2024-10-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20241003_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Status',
            field=models.CharField(choices=[('Fully Paid', 'Fully Paid'), ('Partially Paid', 'Partially Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=15),
        ),
    ]
