# Generated by Django 3.2.6 on 2024-10-04 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
