# Generated by Django 3.2.6 on 2024-10-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_rename_user_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Year_level',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=10, null=True),
        ),
    ]
