# Generated by Django 3.2.6 on 2024-12-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_student_year_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
