# Generated by Django 3.2.6 on 2024-12-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20241207_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Receipt_image',
            field=models.ImageField(upload_to='receipt_images/'),
        ),
    ]
